# Last edited: 2024-12-25
# This is a work in progress and, so, subject to constant change.
site_name: RADNN
site_author: Eduardo Furlan
site_description: radnn repository documentation
site_url: https://efurlanm.github.io/radnn/
repo_name: radnn
repo_url: https://github.com/efurlanm/radnn/
copyright: CC BY 4.0 License
site_dir: docs
docs_dir: src
theme:
    #name: material
    name: readthedocs
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    #palette:
        #primary: grey
        #accent: grey
    features:
        #- header.autohide
        - navigation.instant
        - navigation.tracking   # address show active anchor
plugins:
        - search
extra_css:
    - docs-assets/extra.css
    - docs-assets/katex/katex.min.css
extra_javascript:
    - docs-assets/katex.js
    - docs-assets/katex/katex.min.js
    - docs-assets/katex/contrib/auto-render.min.js
markdown_extensions:
    - tables
    - def_list
    - pymdownx.arithmatex:
        generic: true     # katex
not_in_nav: |
    docs-assets/
exclude_docs: |
    .*
    *§*
    *.F90*
    *.f90*
    *.mod
    *.h
    *.o
    *.nc
    *.py
    *.pyc
    *.npy
    *.sh
    rrtmgp_*
    *.a
    Make*
    *.yml
    *LICENSE*
    *.m
    *.nam
    *.mat
    CONVENTIONS
    *data*
    *.out
    clean
    MODIFICATIONS
    *.cfg
    NOTICE
    TODO
    CHANGELOG
    *variables*
    COPYING
    *.pl
    *.ipynb
    library-zotero/*
validation:
    links:
        not_found: ignore
