model:
  type: torchscript
  parameters:
    filename: "burgers_model.pt"

loss:
  type: torchscript
  parameters:
    filename: "burgers_loss.pt"

optimizer:
  type: adam
  parameters:
    learning_rate: 1e-3
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0
    eps: 1e-8
    amsgrad: 0

lr_scheduler:
  type: cosine_annealing
  parameters:
    T_max: 5000 # Matching num_epochs in burgers_train.f90
